# EdgeFedSim configuration (based on paper)
random_seed: 42
sim_duration: 10000
workflow_arrival_rate: 15

infrastructure:
  power_idle_cpu: 100
  power_max_cpu: 250
  node_configs:
    small_edge: [4, 8]
    medium_edge: [8, 16]
    large_cloud: [32, 128]
  cluster_configs:
    Retail_Edge: {type: small_edge, count: 5}
    Factory_Floor: {type: medium_edge, count: 10}
    Cloud: {type: large_cloud, count: 20}
  network_latency_intra_cluster: 1
  network_bandwidth_intra_cluster: 1000
  network_latency_inter_cluster: 50
  network_bandwidth_inter_cluster: 100
  cloud_node_cost_per_hour: 0.20
  edge_node_cost_per_hour: 0.0

workflow:
  num_workflows: 200
  min_tasks: 20
  max_tasks: 100
  task_cpu_req_range: [0.5, 2.0]
  task_mem_req_range: [0.5, 2.0]
  task_base_runtime_range: [5, 20]
  task_data_size_range: [10, 500]
  container_image_size: 200

scheduler:
  prediction_horizon: 60
  cerebrum_policy_weights:
    performance: {w_perf: 1.0, w_energy: 0.0, w_cost: 0.0}
    energy:      {w_perf: 0.0, w_energy: 1.0, w_cost: 0.0}
    cost:        {w_perf: 0.0, w_energy: 0.0, w_cost: 1.0}
    balanced:    {w_perf: 0.4, w_energy: 0.3, w_cost: 0.3}
  fl_block_latency: 0.5
